### PR TITLE
Add action to automatically build mac and ubuntu binary

### PR DESCRIPTION
**Pull request by DrewDennison**

### CODE REVIEW

**Comment by brendongo** [comment]
After #311 this now works with ubuntu18.04 and after #319 this now packages ubuntu binary in a tar file without breaking builds for mac.

**Comment by ievans** [comment]
Suggestion: increase portability significantly by embedding musl (alpine libc?) eg https://www.systutorials.com/how-to-statically-link-ocaml-programs/ or
or http://rgrinberg.com/posts/static-binaries-tutorial/, cc @aryx for thoughts on how to inject `ocamlopt -ccopt -static`

**Comment by brendongo** [comment]
Merging this as is so future PRs actually have an attached binary. We can add improvements in follow up PRs

**Comment by aryx** [comment]
I actually created a ticket a few months ago to be able to statically link sgrep.
https://github.com/ocaml/opam-repository/issues/15344#issuecomment-603262395
they recently said it was now working.

**Comment by ievans** [comment]
^^ cc @brendongo @DrewDennison

**Pull request merged**
