### PR TITLE
User-defined equivalences in sgrep-core $X + $Y <==> $Y + $X

### PR DESCRIPTION
**Pull request by aryx**

### CODE REVIEW

**Comment by aryx** [comment]
The test plan of the last commit explains the format:
pad@yrax:~/github/sgrep/sgrep$ cat data/basic_equivalences.yml
equivalences:
  # Basic equivalences
  - id: plus-commutative
    pattern: $X + $Y <==> $Y + $X
    languages: [python, javascript, c, go, java]
  - id: eq-to-no-eq
    pattern: $X == $X ==> $X != $X
    languages: [python, javascript, c, go, java]
pad@yrax:~/github/sgrep/sgrep$ yy -equivalences data/basic_equivalences.yml -e '1+2' tests/EQUIV/
+ /home/pad/github/sgrep/sgrep/_build/default/bin/main_sgrep.exe -lang py -equivalences data/basic_equivalences.yml -e 1+2 tests/EQUIV/
/home/pad/github/sgrep/sgrep/tests/EQUIV/test.py:2
   return 1+2
/home/pad/github/sgrep/sgrep/tests/EQUIV/test.py:5
   return 2+1

**Comment by aryx** [comment]
One way to integrate that with sgrep.py is to have in the yaml file in addition to the -rules at the top to also have an -equivalences at the top so that each yaml file can define its own equivalences.
We could also have a shared set of code equivalences in a standard location.

**Comment by ievans** [comment]
amazing work @aryx 

If I were to try to implement https://github.com/returntocorp/sgrep/issues/51, how would that look?

I'm imagining:
```
with open(somefile) as bar:
    ...
<==>
bar = open(somefile)
...
bar.close()
```

Or perhaps this is too complicated to do under this schema?

**Comment by aryx** [comment]
Hmm still some work to be able to do the With rewriting isaac.

**Pull request merged**
